env:
  browser: true
  es2020: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {object-curly-spacing: 0, space-before-function-paren: 0, indent: ['error', 4]}
