name: DeployTestStage

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  deployToTest:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Lint
        run: npx eslint 'src/**/*.ts'
