name: DeployTestStage

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  deployToTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-central-1
      GITHUB_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: rm -rf ./build/ && npx tsc --project tsconfig.json
      - name: Lint
        run: npx eslint src/**/*.ts
