name: MergeNotification

on:
  push:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - name: Releasetool informieren
        run: 'curl https://release-api.devtoday.de/updateSingle --header "Content-Type: application/json" --request POST --data "{ \"repo\": \"${{github.repository}}\" }"'
